### PR TITLE
Update Comment

### PR DESCRIPTION
**Pull request by singhshubham98**

### CODE REVIEW

**Comment by Kissaki** [comment]
I don't really see what this tries to improve/do.

**Comment by Kissaki** [comment]
You can add an 'invalid' label to this PR if you feel like this should not count towards Hacktoberfest - as per their FAQ. I find this PR questionable. Spam. Low effort, no sense, no description, no communication.

> Tag any spam or irrelevant PRs with the "invalid" label to disqualify them.

**Comment by Kissaki** [comment]
The author created 3 other senseless PRs on other projects as well, which further supports this being Spam.

**Comment by mohitkyadav** [comment]
@Kissaki yes, spamming PRs like this, it's kind of annoying. Marking invalid.

**Pull request closed without merging**
