### PR TITLE
Fix js formatting; indent and trailing whitespace

### PR DESCRIPTION
**Pull request by Kissaki**
Indentation should be tabs as per .editorconfig

Trailing whitespace should be emitted

### CODE REVIEW

**Comment by mohitkyadav** [comment]
Please rebase once.

**Comment by Kissaki** [comment]
Rebased. Let's merge/land this first.

**Comment by Kissaki** [comment]
Are you using a squash-merge to land PRs?

**Comment by mohitkyadav** [comment]
Yes.

**Comment by Kissaki** [comment]
Your landing leads to a new commit hash even if a fast forward would be possible and there is nothing to squash. Peculiar.

**Comment by mohitkyadav** [comment]
Yes, I was worried about that, thanks, and don't worry, will just merge from now on. 😅

**Comment by Kissaki** [comment]
No worries. It keeps the author. And for 1-commit PRs it's not too important. Just a little more difficult to identify the commits and branches I can delete in my own repo and locally then.

 On those with multiple commits that make sense I'd like to keep those though with a merge commit.

**Pull request merged**
